### ISSUE TITLE
Extension not showing up in VSCode Marketplace

### ISSUE THREAD

**Issue by cgnaughton** [shorty456132/qsys-vscode-extension#3]
I tried installing your extension from VSCode Marketplace as stated in your installlation instructions, and I am not finding it. Do I have to edit some settings in VSCode to find it?

**Comment by shorty456132** [comment]
hey, sorry about that. Thats what I get for not checking my ai bot... 
I've updated the Readme file to include the proper instructions.  If you're still having issues, let me know.
